[General]
codecs-profiles-selected=
filedialog-path=@Variant(\0\0\0\x11\0\0\0(file:///home/aab/Downloads/playlist.m3u8)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\x1c\0\0\x5\xff\0\0\x3\xbf\0\0\x1H\0\0\x1\xcf\0\0\x3\x9f\0\0\x3r\0\0\0\0\x2\0\0\0\x6\0\0\0\0\0\0\0\0@\0\0\x5\xff\0\0\x3\xbf)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(1536 819)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[OpenDialog]
advanced=false
netMRL=https://iptv-org.github.io/iptv/index.m3u, rtsp://admin:123456@103.84.133.192:554/Streaming/Channels/101, 103.84.133.192
size=@Size(562 443)

[RecentsMRL]
list=https://d3472rjicrodic.cloudfront.net/nlpo/clr-nlpo/709d5260/index.m3u8, https://123tv-mx1.flex-cdn.net/index.m3u8, http://stream.mcquack.net/219/index.m3u8, https://dash2.antik.sk/live/1plus1_marathon/playlist.m3u8, https://dash2.antik.sk/live/test_one_plus_one_int_tizen/playlist.m3u8, "http://158.101.222.193:88/georgia_play.php?id=1plus1international", https://jmp2.uk/plu-62ba60f059624e000781c436.m3u8, https://iptv-org.github.io/iptv/index.m3u, http://88.212.15.27/live/test_trojka_25p/playlist.m3u8, file:///home/aab/Downloads/playlist.m3u8, rtsp://admin:123456@103.84.133.192:554/Streaming/Channels/101, 103.84.133.192
times=0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1
